### ISSUE TITLE
Unhandled exception during 1st phase

### ISSUE THREAD

**Issue by JBScoutBerlin** [nextcloud/backup#107]
I run NC 23.0.0.10 and backup 1.0.0 on PostgreSQL.

I start the backup via CLI with simple `php occ backup:point:create`.  After the last step `maintenance mode: off` I got the error
`An unhandled exception has been thrown:
Error: Call to undefined method OCA\Backup\Service\PointService::getDateDiff() in /var/www/html/office/apps/backup/lib/Service/PointService.php:276`

The stack trace:
`#0 /var/www/html/office/apps/backup/lib/Command/PointCreate.php(114): OCA\Backup\Service\PointService->create(true, '')
#1 /var/www/html/office/3rdparty/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointCreate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/office/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/office/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/office/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Backup\Command\PointCreate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/office/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/office/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/office/console.php(99): OC\Console\Application->run()
#8 /var/www/html/office/occ(11): require_once('/var/www/html/o...')`

**Comment by ArtificialOwl** [comment]
can you send me the result of `./occ app:list` ?

**Comment by vbaz** [comment]
Hi,

I've exact same configuration and same issue. Bellow the output of app:list 

Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - apporder: 0.13.0
  - backup: 1.0.0
  - bookmarks: 10.0.3
  - breezedark: 23.0.0
  - bruteforcesettings: 2.2.0
  - calendar: 3.0.1
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - cms_pico: 1.0.16
  - comments: 1.13.0
  - contacts: 4.0.6
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - encryption: 2.11.0
  - event_update_notification: 1.4.0
  - external: 3.10.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_fulltextsearch: 22.0.1
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - fulltextsearch: 22.0.1
  - fulltextsearch_elasticsearch: 22.0.1
  - geoblocker: 0.5.2
  - integration_dropbox: 1.0.4
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - integration_google: 1.0.6
  - integration_mastodon: 1.0.2
  - integration_onedrive: 1.1.2
  - integration_reddit: 1.0.3
  - integration_twitter: 1.0.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.0
  - maps: 0.1.9
  - news: 17.0.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 3.4.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quicknotes: 0.7.3
  - recommendations: 1.2.0
  - richdocuments: 5.0.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - side_menu: 2.1.0
  - sociallogin: 4.9.5
  - spreed: 13.0.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login: 4.1.0
  - systemtags: 1.13.0
  - talk_matterbridge: 1.23.2
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_totp: 6.2.0
  - twofactor_webauthn: 0.2.14
  - unsplash: 1.2.4
  - updatenotification: 1.13.0
  - user_ldap: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:

Thx for your help

**Comment by parajbs** [comment]
hello JBScoutBerlin

I have exactly the same problems!
I looked at the code in "apps/backup/lib/Service/PointService.php" in line 276, and changed it:

before:
$ this-> o ('> maintenance mode was active for'. $ this-> getDateDiff ($ point-> getDuration ()));
 
after:
$ this-> o ('> maintenance mode was active for'. $ point-> getDuration ());

For me the backup ran through afterwards!

**Comment by ArtificialOwl** [comment]
> * files_fulltextsearch
> * fulltextsearch
> * fulltextsearch_elasticsearch

can you disable those app and try again ?

**Comment by vbaz** [comment]
Ok, I removed the 3 apps and currently running : occ backup:point:create

it should take 1 or 2 hours...

**Comment by ArtificialOwl** [comment]
Ok, i will release a version of FTS for NC23 next week

**Comment by vbaz** [comment]
Ok, no problem anymore after disabling the 3 full text search apps

**Comment by ArtificialOwl** [comment]
fixed since FTS is now available for nc23
