### ISSUE TITLE
TypeError exception during backup:point:create

### ISSUE THREAD

**Issue by jfhg** [nextcloud/backup#111]
I'm trying to setup backup and get the following exception:
``pi@nextcloudpi2:~ $ sudo -u www-data php /var/www/html/nextcloud/occ backup:point:create
> maintenance mode: on
> initialization of the AppData
> initialization of the RestoringPoint: 20211209175232-full-MZHY93aRn1vDLIx based on NC23.0.0.10
> initialization of the storage
> preparation of the data to be stored in the restoring point
> preparation of internal data
> creating chunks
  * data: /ssd1/nextcloud2/data/, 49969 files
> maintenance mode: off
An unhandled exception has been thrown:
TypeError: Unsupported operand types: array & float in /var/www/html/nextcloud/3rdparty/deepdiver/zipstreamer/src/Count64.php:121
Stack trace:
#0 /var/www/html/nextcloud/3rdparty/deepdiver/zipstreamer/src/ZipStreamer.php(387): ZipStreamer\pack64le()
#1 /var/www/html/nextcloud/3rdparty/deepdiver/zipstreamer/src/ZipStreamer.php(396): ZipStreamer\ZipStreamer->buildZip64ExtendedInformationField()
#2 /var/www/html/nextcloud/3rdparty/deepdiver/zipstreamer/src/ZipStreamer.php(343): ZipStreamer\ZipStreamer->buildLocalFileHeader()
#3 /var/www/html/nextcloud/3rdparty/deepdiver/zipstreamer/src/ZipStreamer.php(212): ZipStreamer\ZipStreamer->beginFile()
#4 /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php(463): ZipStreamer\ZipStreamer->addFileFromStream()
#5 /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php(362): OCA\Backup\Service\ChunkService->generateChunk()
#6 /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php(134): OCA\Backup\Service\ChunkService->fillChunks()
#7 /var/www/html/nextcloud/apps/backup/lib/Service/PointService.php(250): OCA\Backup\Service\ChunkService->createChunks()
#8 /var/www/html/nextcloud/apps/backup/lib/Command/PointCreate.php(114): OCA\Backup\Service\PointService->create()
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointCreate->execute()
#10 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#12 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#14 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#15 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#16 /var/www/html/nextcloud/occ(11): require_once('...')

**Comment by mastermns** [comment]
Can you please share your  Backup configuration? Maybe screenshots from the GUI ?

**Comment by jfhg** [comment]
Thanks for looking into this! Screenshots are attached
![Bildschirmfoto vom 2021-12-09 19-23-52](https://user-images.githubusercontent.com/2779637/145454108-38ea9d2a-b6bc-4ea1-8b03-bbf311012f70.png)
![Bildschirmfoto vom 2021-12-09 19-23-30](https://user-images.githubusercontent.com/2779637/145454113-bbc8a0fd-a228-421d-ad7d-458cc908ab97.png)
.

**Comment by mastermns** [comment]
Hello again, 

please share a little more system information? Which Nextcloud Version are you running, which PHP Version is installed? Nginx or Apache?

**Comment by jfhg** [comment]
pi@nextcloudpi2:~ $ apache2 -version
Server version: Apache/2.4.51 (Raspbian)
Server built:   2021-10-07T17:49:44

pi@nextcloudpi2:~ $ php --version
PHP 8.0.13 (cli) (built: Nov 22 2021 09:47:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies

**Comment by mastermns** [comment]
Do you have an additional php7 installed on the machine which you could try. 
In the past I ran into the same issues, with a different app, when using php 8

**Comment by jfhg** [comment]
I'm currently reinstalling with php7.4 but am blocked by https://github.com/nextcloud/backup/issues/116 now. 
I'll report back once I have things working again.

**Comment by jfhg** [comment]
With Backup 1.0.2 and php7.4 I now get a slightly different error:
```

@nextcloudpi2:~ $ sudo -u www-data php /var/www/html/nextcloud/occ backup:point:create 
> maintenance mode: on
> initialization of the AppData
> initialization of the RestoringPoint: 20211217082513-full-eVXAqSKzUFMDjdv based on NC23.0.0.10
> initialization of the storage
> preparation of the data to be stored in the restoring point
> preparation of internal data
> creating chunks
  * data: /data1/nextcloud2/data/, 47106 files
> maintenance mode: off
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\Backup\Model\RestoringChunk::setSize() must be of the type int, float given, called in /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php on line 475 and defined in /var/www/html/nextcloud/apps/backup/lib/Model/RestoringChunk.php:327
Stack trace:
#0 /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php(475): OCA\Backup\Model\RestoringChunk->setSize()
#1 /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php(378): OCA\Backup\Service\ChunkService->generateChunk()
#2 /var/www/html/nextcloud/apps/backup/lib/Service/ChunkService.php(148): OCA\Backup\Service\ChunkService->fillChunks()
#3 /var/www/html/nextcloud/apps/backup/lib/Service/PointService.php(258): OCA\Backup\Service\ChunkService->createChunks()
#4 /var/www/html/nextcloud/apps/backup/lib/Command/PointCreate.php(120): OCA\Backup\Service\PointService->create()
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointCreate->execute()
#6 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#11 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#12 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
pi@nextcloudpi2:~ $ php --version
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
pi@nextcloudpi2:~ $ 
```

**Comment by jfhg** [comment]
https://github.com/nextcloud/backup/pull/124 indeed seems to fix the issue. I was able to create a Restoring Point with that change.
