### ISSUE TITLE
Errors after update from 1.0.0 => 1.0.1 

### ISSUE THREAD

**Issue by tpbraini** [nextcloud/backup#116]
After updating the app from 1.0.0 to 1.0.1 there are 4 error messages popping up.

Restoring points
Settings
App-Data
External Storage
...can't be loaded...

![image](https://user-images.githubusercontent.com/32675610/145878447-c0f76098-39c5-4ce3-ac53-fedbd71fa95c.png)

App can't be used anymore

**Comment by rinal13** [comment]
Have the same issue which also resulting in "occ cli" Segmentation fault
Seems that the cron goes to an infinite loop

**Comment by ProjektCamping** [comment]
i am just heading exactly the same problems. Does somebody know solution for this. @rinal13 how do you come up with the idea that it is a infinite loop of the cron task?

**Comment by rinal13** [comment]
It's only a first guess, as the cron job takes longer as usual when backup app get activated,
and the CLI get an segmentation fault which is an indication that there is an memory issue,
which is mostly caused by an infinite loop which eats up the available memory.
If the backup app is deactivated the issue is gone.

**Comment by morskipas** [comment]
I have exactly the same error

**Comment by EVOTk** [comment]
Same error :(

**Comment by parajbs** [comment]
I have exactly the same error, with the new version 1.0.1 !

**Comment by balrobs** [comment]
Same issue here!

**Comment by Spoonler** [comment]
I have also the same error after updating from 1.0.0 to 1.0.1

**Comment by Bewob** [comment]
I have exactly the same error, with the new version 1.0.1 after new instal

**Comment by jakobroehrl** [comment]
same problem

**Comment by samuelcanadi** [comment]
same here

**Comment by thomasesr** [comment]
Same

```
Process 50289 (apache2) of user 33 dumped core.
Stack trace of thread 77:
    #0  0x00007f06c253050b n/a (n/a + 0x0)
```

**Comment by Maffsie** [comment]
Yep, same error. I put it down to something in my environment, but I guess it is a more widespread issue. Using the official nextcloud docker image (`nextcloud:23`) with APCu for local memcache and redis for all other caches, after installing and enabling Backup 1.0.1, `./occ` reliably segfaults regardless of what arguments are given, the settings page for backups doesn't populate with any config options, I get the same four errors, and no settings can be saved.

I had issues with saving settings on 1.0.0 which is why I assumed it was something in my environment.

**Comment by ricardoretsos** [comment]
> After updating the app from 1.0.0 to 1.0.1 there are 4 error messages popping up.
> 
> Restoring points Settings App-Data External Storage ...can't be loaded...
> 
> ![image](https://user-images.githubusercontent.com/32675610/145878447-c0f76098-39c5-4ce3-ac53-fedbd71fa95c.png)
> 
> App can't be used anymore

Same Error !!

**Comment by rinal13** [comment]
I found following error in my apache log which also points to a buggy php code which causes the server run out of memory

> [Tue Dec 14 22:56:02.056682 2021] [proxy_fcgi:error] [pid 79395:tid 140116225783552] [client 192.168.21.2:55581] AH01067: Failed to read FastCGI header
> [Tue Dec 14 22:56:02.056762 2021] [proxy_fcgi:error] [pid 79395:tid 140116225783552] (104)Connection reset by peer: [client 192.168.21.2:55581] AH01075: Error dispatching request to :

**Comment by kdomke** [comment]
Any way to help to resolve the problem? I have the same problem here and would really like to use the backup extension

**Comment by ArtificialOwl** [comment]
I will release 1.0.2 today

**Comment by tpbraini** [comment]
> I will release 1.0.2 today

After update to 1.0.2...

3 errors are gone, 1 is still there...
![image](https://user-images.githubusercontent.com/32675610/146385542-20b815f4-3635-4bc1-af7a-7350266b8f75.png)


root: /var/www/nextcloudtest# sudo -u www-data php occ backup:point:list
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Backup\Service\CronService::getRPFromInstances() in /var/www/nextcloudtest/apps/backup/lib/Command/PointList.php:119
Stack trace:
#0 /var/www/nextcloudtest/3rdparty/symfony/console/Command/Command.php(255): OCA\Backup\Command\PointList->execute()
#1 /var/www/nextcloudtest/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#2 /var/www/nextcloudtest/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#3 /var/www/nextcloudtest/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/nextcloudtest/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /var/www/nextcloudtest/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /var/www/nextcloudtest/console.php(99): OC\Console\Application->run()
#7 /var/www/nextcloudtest/occ(11): require_once('/var/www/nextcl...')

**Comment by morskipas** [comment]
After update to 1.0.2 I got the following error

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/6042276/146404839-98568e7b-2a35-444d-852b-a77e4c6a39e1.png">

**Comment by corincorvus** [comment]
The error persist on 1.0.2
![grafik](https://user-images.githubusercontent.com/21257329/146407677-d761c886-92ae-4ac5-8cbe-89cb8c7bbfb5.png)

**Comment by Martin5651** [comment]
After updating to version 1.0.2 I get the same error message as @morskipas

**Comment by simon-kaiser** [comment]
Same error as @morskipas and @corincorvus

**Comment by ArtificialOwl** [comment]
should be ok with 1.0.3
