### ISSUE TITLE
Causes memory errors in occ when enabled

### ISSUE THREAD

**Issue by m2mexpert** [nextcloud/backup#118]

**Comment by m2mexpert** [comment]
Using PHP 7.4.26
Nextcloud 23.0.0
Docker container

example command 
 sudo -u abc /usr/bin/php /config/www/nextcloud/occ -V

When enabled occ will fail on any command with:

PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 78
root@67f6f8c79f1f:/config/www/nextcloud# sudo -u abc /usr/bin/php /config/www/nextcloud/occ
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 106
root@67f6f8c79f1f:/config/www/nextcloud# sudo -u abc /usr/bin/php /config/www/nextcloud/occ
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 78

**Comment by obrb** [comment]
I have a similar or probably the same issue on my test server running Debian 11 Bullseye without Docker. If the backup app is enabled, any OCC command gets aborted with a "Segementation Fault".  When I disable the app in the WebUI, the OCC command gets executed normally. 

Debian 11 Bullseye
Nextcloud 23.0.0
Nextcloud Backup 1.0.1
Apache 2.4.51
PHP 8.03
MariaDB 10.5

**Comment by martadinata666** [comment]
Same issue, just removed backup apps it `occ` command work again.

**Comment by ArtificialOwl** [comment]
fixed in 1.0.3
