### ISSUE TITLE
App not listed in app store?

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/backup#12]
The app is not listed in the app store https://apps.nextcloud.com/?search=backup ?
Maybe not properly categorized?

**Comment by Shamalamadindong** [comment]
Still not listed as of today

**Comment by ArtificialOwl** [comment]
will be available for NC23

https://github.com/nextcloud/app-certificate-requests/commit/bd125cf71691d5212e7a2961da69fb63203be923
