### ISSUE TITLE
when copying custom_apps, apps/ folder is included a second time in the backup

### ISSUE THREAD

**Issue by parajbs** [nextcloud/backup#121]
hello

why is the backup so full? Two backups of folder apps? Two backups of folder custom_apps?
see below picture!

![Screenshot (1001)](https://user-images.githubusercontent.com/8345125/146484681-0307f7ee-f36b-46aa-bf48-17b16868521e.png)

both backups of folder apps are included in the full backup!
both have the same size / number of files!
this makes the backup unnecessarily larger!
or why?

the nextcloud backup also contains the custem_apps folder, which makes the backup even bigger!

what's going on there?

please help

**Comment by ArtificialOwl** [comment]
So, it seems that during the backup of custom_apps, the original apps folder is copied again, this is a bug.

The custom_apps folder will be backup if it exists, which is a logical part of the process.
