### ISSUE TITLE
remote backup includes zip and plain data

### ISSUE THREAD

**Issue by jrodan** [nextcloud/backup#123]
Hi, 

this night finally the backup works. 
The issue is, that not only the zip package was transmitted but also the plain files: 
<img width="585" alt="Bildschirmfoto 2021-12-17 um 09 42 24" src="https://user-images.githubusercontent.com/6048704/146515812-871f7039-8671-4aa5-8074-74655b9b4cc3.png">

For me the zip file would be perfectly enough. What is the required state?

**Comment by ArtificialOwl** [comment]
The first pass does not compress/encrypt your data: https://github.com/nextcloud/backup/blob/master/README.md#external-appdata

you data is here, it will be encrypted/compressed during the second pass.
The app.zip is not used yet and only contains the current backup app from your nextcloud
