### ISSUE TITLE
unable to use smb external share

### ISSUE THREAD

**Issue by graphius** [nextcloud/backup#126]
I can mount the external share from within Nextcloud, however backup will not show any external drives
when I try occ backup:external:list or really any backup:external:* 
I get 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/1181676/146697198-78d2988c-8366-4812-93e8-1b4740d6a025.png">

Help?

**Comment by ArtificialOwl** [comment]
can you run it with `-v` and send me the full result ?

**Comment by ArtificialOwl** [comment]
should be fixed in next release
