### ISSUE TITLE
No retention policy lower than 5 for external storage

### ISSUE THREAD

**Issue by nunesgh** [nextcloud/backup#134]
Hi,

My Nextcloud instance is version 23.0.0 and the Backup app is version 1.0.3.

I am trying to set a retention policy for external storage lower than the default, currently set to 5. But even though I receive the confirmation that the new value has been saved, it has not.

Is this retention policy of 5 days intentional?

Thank you for your attention.

**Comment by runhappy1500** [comment]
Same on my side.

**Comment by ArtificialOwl** [comment]
confirming there is something missing.

In the meanwhile: `./occ config:app:set backup store_items_external --value <your_value>`

Please note also that this is not the number of days, but the number of RP kept when purging

**Comment by Gamemap** [comment]
Larger values are also not supported.

**Comment by ArtificialOwl** [comment]
ahah, yes .. found the issue i'll work on this asap
