### ISSUE TITLE
fail Call to undefined function OCA\Backup\Service\sodium_memzero()

### ISSUE THREAD

**Issue by Eric-Sparks** [nextcloud/backup#137]
I am noticing that when my backups run, automatically, they don't get uploaded to the external storage.  I kicked off a backup manually last night and it was successful.  I manually tried to pack it but I received this error:

```
# sudo -u www php ./occ backup:point:pack 20211230055159-full-RZldfJTA3NoBikO

Packing Restoring Point 20211230055159-full-RZldfJTA3NoBikO
 > lock and set status to processing
 > Browsing RestoringData data
   > Packing RestoringChunk data-7cc4a38e-78f1-425c-bff4-ee64a00fa680: proceeding
     * copying chunk to temp file /tmp/php0acnfW: ok
     * compressing /tmp/php0acnfW: /tmp/phpKvL201
     * spliting /tmp/phpKvL201 in parts: 40 part(s) 
     * encrypting each part
       . encrypting /tmp/phppdZwvX: fail Call to undefined function OCA\Backup\Service\sodium_memzero()

In PackService.php line 210:
                                                                                                                             
  issue on chunk data-7cc4a38e-78f1-425c-bff4-ee64a00fa680 - Call to undefined function OCA\Backup\Service\sodium_memzero()  
```

Not sure how to remedy this.  I'm assuming this is why the automated backups aren't being completed.

**Comment by mastermns** [comment]
Hello,

please check if you have the module php sodium installed.   

php -m | grep -i sodium

if not installed please install. 

Cheers

**Comment by ArtificialOwl** [comment]
It is strongly adviced to install sodium, but if sodium is missing there should be some fallback to openssl+cbc. Theorically.

Please try this patch #149

**Comment by Eric-Sparks** [comment]
> Hello,
> 
> please check if you have the module php sodium installed.
> 
> php -m | grep -i sodium
> 
> if not installed please install.

Yes, this fixed the problem, thanks!  I wonder if there shouldn't be some sort of notification on the Administration Overview page when one of the packages, like this, is missing.
