### ISSUE TITLE
Chunk Filesize

### ISSUE THREAD

**Issue by mastermns** [nextcloud/backup#141]
Hello,

the current chunk file size is 100Mb which creates a lot of files on my systems. Since my internet upload speed is fast and stable I was wondering if there is a parameter to increase the chunk file size. 

I saw that the UploadService.php  has a const "PACK_SIZE = 100000" - is this the correct path to change the chunk file at the moment or will this mess-up more then it will improve. 

Thanks in advance

**Comment by ArtificialOwl** [comment]
you can change the value using:

`./occ config:app:set backup chunk_part_size --value 100`
