### ISSUE TITLE
Undefined variable $user at /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900

### ISSUE THREAD

**Issue by Mister-Muffin** [nextcloud/backup#152]
```
[PHP] Error: Undefined variable $user at /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900

GET /ocs/v2.php/apps/backup/external
from 172.25.0.2 by user at 2022-01-04T16:34:53+01:00
```

After the full backup is started, several of the error messages quoted above appear. Nextcloud also briefly goes into maintenance mode, but leaves it again immediately and the backup aborts. A friend has the same problem.
![grafik](https://user-images.githubusercontent.com/45641704/148086949-1ddf020d-f4e6-4d71-9400-f1be98162eb5.png)
 Feel free to ask for more information. :)
Thanks!

**Comment by zamants** [comment]
I got the same error, this is the stacktrace. 

![afbeelding](https://user-images.githubusercontent.com/50657671/148439994-e3230624-db50-4175-b198-5659463b8ad4.png)

**Comment by JoergPalmer** [comment]
I'm having the same issue ..

v1.0.4 on nextcloud v23.0.0

Backup target on external storage
Local data on local storage.

**Comment by bensuchy** [comment]
I get the same issue with the same stacktrace as zamants.
Nextcloud 23.0.0
Backup 1.0.4

Backup target and app data on external storage.

The external storage is locally mounted, so I wonder if that is the issue (no user is necessary to "login" to this external storage). I did switch my app data to "Local storage" to test and although I still got these errors, I did see a scheduled backup show up in the local storage folder.

**Comment by mastermns** [comment]
Deleting the variable `$user`  did have no impact on the functionality for me but obviously does not throw the error messages anymore. 

`line 899: $storage->getAuthMechanism()->manipulateStorageConfig($storage);`
`line 900: $storage->getBackend()->manipulateStorageConfig($storage);`

**Comment by ggamehdtv** [comment]
Is there a fix for this? Receiving the same error on nextcloud 23, php7.4. When trying to backup to another nextcloud instance.

**Comment by adymorz** [comment]
> Is there a fix for this? Receiving the same error on nextcloud 23, php7.4. When trying to backup to another nextcloud instance.

Just leave a thumbs up on the issue to signal that you are affected too, and wait or contribute!

**Comment by arg** [comment]
I'm seeing this issue too when I try to setup backup to external storage. No matter which external target I pick: S3, SMB or even local (which doesn't require user credentials to be set at all) the initial backup, triggered by **Create full restoring point** button, fails with this message in logs:

```json
{
  "reqId": "99ElLEfuviwv9ZUIteu0",
  "level": 3,
  "time": "2022-01-20T14:03:56+00:00",
  "remoteAddr": "192.168.100.6",
  "user": "admin",
  "app": "PHP",
  "method": "POST",
  "url": "/ocs/v2.php/apps/backup/appdata",
  "message": "Undefined variable: user at /config/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900",
  "userAgent": "Mozilla/5.0 (X11; FreeBSD amd64; rv:95.0) Gecko/20100101 Firefox/95.0",
  "version": "23.0.0.10",
  "exception": {
    "Exception": "Error",
    "Message": "Undefined variable: user at /config/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900",
    "Code": 0,
    "Trace": [
      {
        "file": "/config/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php",
        "line": 900,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/config/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php",
        "line": 822,
        "function": "prepareStorageConfig",
        "class": "OCA\\Backup\\Service\\ExternalFolderService",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php",
        "line": 865,
        "function": "getStorages",
        "class": "OCA\\Backup\\Service\\ExternalFolderService",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/apps/backup/lib/Service/PointService.php",
        "line": 744,
        "function": "getStorageById",
        "class": "OCA\\Backup\\Service\\ExternalFolderService",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/apps/backup/lib/Controller/LocalController.php",
        "line": 273,
        "function": "setExternalAppData",
        "class": "OCA\\Backup\\Service\\PointService",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "setAppData",
        "class": "OCA\\Backup\\Controller\\LocalController",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/config/www/nextcloud/ocs/v1.php",
        "line": 62,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/config/www/nextcloud/ocs/v2.php",
        "line": 23,
        "args": [
          "/config/www/nextcloud/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/config/www/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "id": "61e96bcfab562"
}
```
My setup:
* Nextcloud 23.0.0 (Linuxserver's distribution)
* PHP 7.4.26
* MariaDB 10.6.5
* Backup 1.0.4

**Comment by crashbandicode** [comment]
I am also having this issue

**Comment by CptDelay** [comment]
Same here. Setup:
- Nextcloud 23.0.0 (using the official Docker Image with Apache)
- mariadb 10.5
- PHP 8.0.15
- Backup 1.0.4

appdata backup location is a mounted docker volume on a local drive.
external backup location is a s3 compatible storage.

Log Entry:
```reqId: OhO4xqLl20qkkZ4eN7ut
level: 3
time: '2022-01-22T17:51:13+00:00'
remoteAddr: 172.19.0.2
user: markus
app: PHP
method: GET
url: /ocs/v2.php/apps/backup/external
message: >-
  Undefined variable $user at
  /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php#900
userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0'
version: 23.0.0.10
exception:
  Exception: Error
  Message: >-
    Undefined variable $user at
    /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php#900
  Code: 0
  Trace:
    - file: /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php
      line: 900
      function: onError
      class: OC\Log\ErrorHandler
      type: '::'
      args:
        - 2
        - Undefined variable $user
        - /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php
        - 900
    - file: /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php
      line: 822
      function: prepareStorageConfig
      class: OCA\Backup\Service\ExternalFolderService
      type: '->'
      args:
        - __class__: OCA\Files_External\Lib\StorageConfig
    - file: /var/www/html/custom_apps/backup/lib/Controller/LocalController.php
      line: 288
      function: getStorages
      class: OCA\Backup\Service\ExternalFolderService
      type: '->'
      args: []
    - file: /var/www/html/lib/private/AppFramework/Http/Dispatcher.php
      line: 217
      function: getExternalFolder
      class: OCA\Backup\Controller\LocalController
      type: '->'
      args: []
    - file: /var/www/html/lib/private/AppFramework/Http/Dispatcher.php
      line: 126
      function: executeController
      class: OC\AppFramework\Http\Dispatcher
      type: '->'
      args:
        - __class__: OCA\Backup\Controller\LocalController
        - getExternalFolder
    - file: /var/www/html/lib/private/AppFramework/App.php
      line: 157
      function: dispatch
      class: OC\AppFramework\Http\Dispatcher
      type: '->'
      args:
        - __class__: OCA\Backup\Controller\LocalController
        - getExternalFolder
    - file: /var/www/html/lib/private/Route/Router.php
      line: 302
      function: main
      class: OC\AppFramework\App
      type: '::'
      args:
        - OCA\Backup\Controller\LocalController
        - getExternalFolder
        - __class__: OC\AppFramework\DependencyInjection\DIContainer
        - _route: ocs.backup.Local.getExternalFolder
    - file: /var/www/html/ocs/v1.php
      line: 62
      function: match
      class: OC\Route\Router
      type: '->'
      args:
        - /ocsapp/apps/backup/external
    - file: /var/www/html/ocs/v2.php
      line: 23
      args:
        - /var/www/html/ocs/v1.php
      function: require_once
  File: /var/www/html/lib/private/Log/ErrorHandler.php
  Line: 92
  CustomMessage: '--'
id: 61f180cc1d983
```

**Comment by arg** [comment]
I tried to setup backups to external storage one more time, following [the guide](https://github.com/nextcloud/backup#upload-to-external-storages) but again, that didn't work. So it looks like currently backing up to any external storage is completely broken. Can anyone take a look? @ArtificialOwl?

**Comment by erik78se** [comment]
The problems is here. Not sure what to do about it:
```

/**
         * Process storage ready for mounting
         * based on apps/files_external/lib/Config/ConfigAdapter.php
         *
         * @param StorageConfig $storage
         *
         * @throws InsufficientDataForMeaningfulAnswerException
         * @throws StorageNotAvailableException
         * @throws QueryException
         */
        private function prepareStorageConfig(StorageConfig &$storage) {
                foreach ($storage->getBackendOptions() as $option => $value) {
                        $storage->setBackendOption($option, MountConfig::substitutePlaceholdersInConfig($value));
                }

                $objectStore = $storage->getBackendOption('objectstore');
                if ($objectStore) {
                        $objectClass = $objectStore['class'];
                        if (!is_subclass_of($objectClass, '\OCP\Files\ObjectStore\IObjectStore')) {
                                throw new \InvalidArgumentException('Invalid object store');
                        }
                        $storage->setBackendOption('objectstore', new $objectClass($objectStore));
                }
                $storage->getAuthMechanism()->manipulateStorageConfig($storage, $user);
                $storage->getBackend()->manipulateStorageConfig($storage, $user);
        }

```

**Comment by erik78se** [comment]
I was able to perform some kind of backup by setting **user = null;**

Which is probably not what you need when dealing with anything but local storage I guess....

Its also not showing any backup history, but some files has been created.

```
user = null;
$storage->getAuthMechanism()->manipulateStorageConfig($storage, $user);
$storage->getBackend()->manipulateStorageConfig($storage, $user);

```

**Comment by crashbandicode** [comment]
Does anyone have a working backup configuration at all? (with or without Docker). Would be good to compare the differences.

**Comment by tullsta2** [comment]
Just wanted to confirm this behavior for NC 23.0.1 (official docker) + backup 1.0.4:

```
Error PHP	Error: Undefined variable $user at /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php#900
ErrorPHP	Error: Undefined variable $user at /var/www/html/custom_apps/backup/lib/Service/ExternalFolderService.php#899
```
Did follow the "known issues"-recommendation from the git manual, i.e. I browsed to the sftp-dir in the NC file app and was able to e.g. create a dir there.

**Comment by TimHausmann** [comment]
Same issue here

v1.0.4 on nextcloud v23.0.0

Backup target on S3 compatible storage (Backblaze)
Local data on local storage.

**Comment by n0bbi** [comment]
Same Issue with backup v1.0.4 on Nextcloud 23.0.1 

Target: ftps-directory

**Comment by martin-77** [comment]
Same Isssue here

Setup: Nextcloud 23.0.1
PHP 8.0.14
MariaDB 10.5.13

Backup v1.0.4
BackupStorage mounted via SMB - Files can be generated on the Nextcloud Gui - read-write works

Started Backup Stucks - Button to start Backup is "blued out", Storage can not be changed (leads to error)

Error in Log:
Error: Undefined variable $user at /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900

`Error: Undefined variable $user at /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900

    /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php - line 900:

    OC\Log\ErrorHandler::onError()

    /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php - line 822:

    OCA\Backup\Service\ExternalFolderService->prepareStorageConfig()

    /var/www/nextcloud/apps/backup/lib/Controller/LocalController.php - line 288:

    OCA\Backup\Service\ExternalFolderService->getStorages()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

    OCA\Backup\Controller\LocalController->getExternalFolder()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /var/www/nextcloud/ocs/v1.php - line 62:

    OC\Route\Router->match()

    /var/www/nextcloud/ocs/v2.php - line 23:

    require_once("/var/www/nextcloud/ocs/v1.php")`

**Comment by cybergitti** [comment]
I am suffering as well with a never working backup app 1.04 on nextcloud 23 self hosted.
not even on local disk...  any solution?

**Comment by Omaha2002** [comment]
Same error here, is every one else using app Group folders?

**Comment by tullsta2** [comment]
> Same error here, is everyone else using app Group folders?

yes.

**Comment by emrahyildirim** [comment]
Every once in a while, I sit back and look at the app, it looks beautiful :-) ... Even if the application doesn't work, its existence is enough :-)

**Comment by n0bbi** [comment]
> Same error here, is everyone else using app Group folders?
> 
> For me it does create a backup, external storage is external connection to other Nextcloud server but I do get the same undefined variable $user error in my logs.

No.

**Comment by iwanzarembo** [comment]
@TimHausmann The packaging takes a lot of time. But the full backup was successful in the end.

**Comment by mastermns** [comment]
If i am not mistaken    backup, packing & encryption, uploading are 3 different workstreams and are triggered by independent  cron jobs - so this can take a moment

**Comment by discoverSlow** [comment]
Hi, 

I had set up an SFTP external storage and verified that it works correctly. NC version 23.0.2.

Then I configured the sftp storage in the backup app (V 1.0.4) . When starting the initial backup ("Vollständigen Wiederherstellungspunkt herstellen") I get the same error as mentioned above  
<html><body>


Fehler | PHP | Error: Undefined variable $user at /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900/var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php - line 900: OC\Log\ErrorHandler::onError()/var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php - line 822: OCA\Backup\Service\ExternalFolderService->prepareStorageConfig()/var/www/nextcloud/apps/backup/lib/Controller/LocalController.php - line 288: OCA\Backup\Service\ExternalFolderService->getStorages()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217: OCA\Backup\Controller\LocalController->getExternalFolder()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/ocs/v1.php - line 62: OC\Route\Router->match()/var/www/nextcloud/ocs/v2.php - line 23: require_once("/var/www/nextcloud/ocs/v1.php")
-- | -- | --



</body>
</html>

**Comment by iwanzarembo** [comment]
@discoverSlow Would you mind trying to remove the user variable? Then we would have another test of the backup functionality.

**Comment by cybergitti** [comment]
I doubt that so many people did a misconfiguration.

But if so, what can that be? I used simple straight installation in Ubuntu, PHP 8.0, MySQL ...

 

would be interesting to find the difference in configs...

 

Gesendet: Mittwoch, 02. März 2022 um 15:49 Uhr
Von: "crashbandicode" ***@***.***>
An: "nextcloud/backup" ***@***.***>
Cc: "cybergitti" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [nextcloud/backup] Undefined variable $user at /var/www/nextcloud/apps/backup/lib/Service/ExternalFolderService.php#900 (Issue #152)


 

So I'm playing around with a test docker nextcloud instance (nextcloud:apache) without a reverse proxy and it appears to work without the errors we've been seeing. Perhaps there's a misconfiguration in our reverse proxies?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nextcloudfan** [comment]
Same here, latest NC 23, latest backup App, latest PHP 8.0, latest Maria 10.6, Ubuntu 20.04

**Comment by tullsta2** [comment]
>Perhaps there's a misconfiguration in our reverse proxies

If that would be the case, why would then the external storage work as such, i.e. when not being used from w/in backup?

**Comment by nextcloudfan** [comment]
No misconfiguration. Buggy app!

**Comment by emrahyildirim** [comment]
So many people configured it wrong :-) Anyone configured it correctly? I wasn't going to drink that last glass while I was structuring, it was definitely from him :-?

**Comment by ph00lt0** [comment]
> Same error here, is everyone else using app Group folders?
> 
> For me it does create a backup, external storage is external connection to other Nextcloud server but I do get the same undefined variable $user error in my logs.

Yep also group folders here. But I just tried to back up to local storage, same error. I wouldn't be surprised if this app hasn't been tested properly with group folders.

**Comment by nextcloudfan** [comment]
Which testing?? The result shows clearly there was no testing!

**Comment by JoergPalmer** [comment]
Not that important ... but that is it for me! Enough is enough! This app is now wiped from my server.

I was facing the very same problem and NEVER got a single backup to work. The app was sitting in the background, disabled. Today I received an update notification (to v1.0.5) and was full of hope this might be helping. Boy, was I wrong! After the update, my nextcloud instance went to maintenance mode and never returned. Particularly annoying when you are on the road and all syncing leads to nothing!

Being back home now, the first thing to do was to eliminate this app. To me, it is good for nothing ... all the best for you!

**Comment by JoergPalmer** [comment]
If #228 really is about the php version, I'm on php v8.0.17.

On a lighter note, I had disabled the app with the occ command.

**Comment by purerstamp** [comment]
_I'm also very frustrated about this app but please guys, don't be so rude. All this is maintained by wonderful people mostly on their free time. Some comments are tough beside they don't help and encourage neither._

**Comment by JoergPalmer** [comment]
> _I'm also very frustrated about this app but please guys, don't be so rude. All this is maintained by wonderful people mostly on their free time. Some comments are tough beside they don't help and encourage neither._

You are right, and I apologize. I was carried away by disappointment. I changed my comment, and I really didn't mean to sound harsh.

**Comment by ArtificialOwl** [comment]
1.0.6 is on the release track, as it seems that the main subject of this one is lost in discussion, please open a new ticket if you still have issues with external storage and/or upload of your backups.
