### ISSUE TITLE
When will the backup be packed?

### ISSUE THREAD

**Issue by Gamemap** [nextcloud/backup#153]
I am testing the Nextcloud server on a virtual machine. Only once the backup was automatically packed. Can you tell me when this happens automatically (specific time?) or if the packing should start immediately?

Is it possible to set these things? (pack time, pack immediately)
Maybe this information can be written in a documentation.

**Comment by mastermns** [comment]
Packing starts after the first  job (creating, encryption, split) and before the second job (upload)

**Comment by Gamemap** [comment]
> Packing starts after the first job (creating, encryption, split) and before the second job (upload)

Thank you

Everything works, I just had to wait a little longer.

**Comment by Exagone313** [comment]
I'm getting the same issue, is there a way to get some progress on when the backup will be uploaded to the external storage?

**Comment by Gamemap** [comment]
@Exagone313 I waited a few hours until the backup was packed. I think there will be an green check mark but I don't use a external storage at the moment. If you search for external (https://github.com/nextcloud/backup/issues?q=is%3Aissue+is%3Aopen+external), you can see that there are several problems.
