### ISSUE TITLE
Implement as Backup Solution

### ISSUE THREAD

**Issue by reiner-text** [nextcloud/backup#18]
Is it possible to make this tiny and helpful app compatible with NC17/18 and implement this app into the server for future versions?

It makes sense for me to has a simple backup solution in the Admin section to save a database dump before I make some actions on the instance. It would also be helpful for Admins in a Shared Hosting environment without or limited SSH access.
Other backup solutions (3rd party) are overloaded with functions, automated backup plans and so on.

**Comment by IzumiSena** [comment]
hoping this goes live soon

**Comment by ArtificialOwl** [comment]
You might be interested to test the app for NC23.
Do not hesitate to create a new 'request' for each missing feature.
