### ISSUE TITLE
Wrong field reference in German translation of UI text, eventually other languages too

### ISSUE THREAD

**Issue by Vrumf0ndel** [nextcloud/backup#224]
![Screenshot 2022-03-19 141544](https://user-images.githubusercontent.com/101066609/159122677-0c06a016-fe92-45f3-88c2-cac38a66339e.png)

The field reference in the text to the **days as interval for partial backups** is linked to the field **days as interval for full backups**.
Found in German translation. Possibly other languages are also affected.

Nextcloud: 23.0.2.1
Backup: 1.0.4

**Comment by Vrumf0ndel** [comment]
The field reference {delayFullRestoringPoint} needs to be replaced by {delayPartialRestoringPoint} for the partial restoring point text (text 55). I've found the related text in Transiflex, but it's write protected. So I've raised an issue there.

**Comment by nickvergessen** [comment]
Fixed german translation
