### ISSUE TITLE
Version 1.0.5 depends on PHP >= 7.4.0

### ISSUE THREAD

**Issue by nunesgh** [nextcloud/backup#228]
Hi there,

I have just updated to version 1.0.5 and now my whole Nextcloud instance is broken.

```
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
```

At the top of the screen, there is also the following:
`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".`

I will try to manually disable the app now, but this is just a mess.

**Comment by nickvergessen** [comment]
@ArtificialOwl seems like https://github.com/nextcloud/backup/pull/185 was merged in the assumption that this app would follow the stable branch pattern. I guess you need to revert it and change your composer dependencies with an update

**Comment by Vrumf0ndel** [comment]
@nunesgh An updated version 1.0.6 is available now for installation. This should fix the PHP issue.

**Comment by nunesgh** [comment]
> @nunesgh An updated version 1.0.6 is available now for installation. This should fix the PHP issue.

Thank you!!
