### ISSUE TITLE
No connection to server

### ISSUE THREAD

**Issue by andcor** [nextcloud/backup#243]
Hi

I have just installed the backup app in my nextcloud install (Truenas scale comunity kubernetes installation with postgress in different container than nextcloud itself). But I get the following error when the application goes into maintenance mode and tries to make a backup:

[cron] Error: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 7 no connection to the server

The nextcloud server itself has no problems connecting to the database server and I cannot see anywhere where I can inform the backup app of my database settings.

Any help would be appreciated

Kind regards

Andreas

**Comment by nickistre** [comment]
I am coming across this issue myself.  Running Nextcloud in a Docker environment, also with postgres in a different container than nextcloud itself, and the same error in my logs.  I'll go through my log files and try to extract more info.

**Comment by bfontaine** [comment]
Did you end up fixing the issue?

**Comment by andcor** [comment]
No, I simply ended up abandoning nextcloud and truenas for a while. Mostly because the server it were running on is too expensive to keep running 24/7

**Comment by andcor** [comment]
Closed as it is stale
