### ISSUE TITLE
Invaild key 

### ISSUE THREAD

**Issue by shruuub** [nextcloud/backup#262]
Hello! So I tried to backup my main instance on a vm (for testing purposes), and therefor ran the command:
```
docker exec -it --user 33 nextcloud ./occ backup:setup:import --key my_key_is_here < ./settings.asc
``` 
I've tried it multiple times with different files, always the same result:
```
In SetupImport.php line 126:
               
  Invalid Key  
               

backup:setup:import [--key KEY]
```
Inserting a random string does actually cause a different error, so they key must work to some degree. Is there anything special about entering the key?
Thanks for helping :)

**Comment by LeLuc4** [comment]
It is a problem with docker. Maybe some parsing issue. Just do it from inside the container. 
Exec into the docker container and do the restore from there:
`docker exec --user www-data -it nextcloud_app_container /bin/sh`
Paste your settings.asc into a local file:
`vim settings.asc` and paste your file.
Import:
`php occ backup:setup:import --key your_key < ./settings.asc`

**Comment by shruuub** [comment]
> 

Sounds good, thanks for your reply,  I'll try that later :)

**Comment by th-2021** [comment]
I ran into the same. The issue imho is that the key is saved in backup.setup as well (when run via occ). Deleting the key from backup.setup solved it. Maybe the key should be written to stderr?

**Comment by th-2021** [comment]
Ok, I found it. I shouldn't  pass -t with docker exec.
