### ISSUE TITLE
After running Backup Server gives Internal Error (500)

### ISSUE THREAD

**Issue by subroutineox** [nextcloud/backup#263]
I am sorry if this is the wrong place to ask for help. And i dont know if this is a bug... 
I ran the Backup App and my Server locked because it seems to have run out of space (500 Internal Server Error).
Could anyone tell me where i can find and delete the local Backup File to get the Cloud back up running?  Thanks in advance!

**Comment by Githopp192** [comment]
check your <nc-data-folder>/appdata_ocxxxxxxxxxx/backup

there is also a command: (it never tried it - so i do not know, what happens exactly !):

occ backup:reset

WARNING! You are about to delete all data (and Restoring Point) related to the Backup App!
Do you really want to reset the Backup App? (y/N) y

WARNING! This operation is not reversible.
Please confirm this destructive operation by typing 'reset':
