### ISSUE TITLE
How to completely and safely remove the Backup App

### ISSUE THREAD

**Issue by FernandoMarques-Santos** [nextcloud/backup#309]
Hi,

I recently had some problems with the app. How can I remove the app safely? Can I uninstall it like any other app? There is no documentation for it.

Context:
I had problems such as it creating dozens of partial backups even though it was configured to do this once a week (I suspect because I left Policy for the local app data set to zero).  Anyway, after I deleted those backups (which were still in the App folder - never managed to go to restore point folder), nextcloud went offline for some time, which freaked me out (not the maintenance thing - it just timed out). I almost tried to roll the backup (such an irony), but at the last second it went online again.

I am glad the app exists, and praise the effort in creating it. However, in my case I found it a bit risky for now. I will definitely try again in the future.

Here are the errors when it went offline:

>[backup] Error: error while running differential backup - [{"file":"\/var\/www\/nextcloud\/apps\/backup\/lib\/Cron\/Backup.php","line":126,"function":"runDifferentialBackup","class":"OCA\\Backup\\Cron\\Backup","object":{},"type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/backup\/lib\/Cron\/Backup.php","line":115,"function":"runBackup","class":"OCA\\Backup\\Cron\\Backup","object":{},"type":"->","args":[1652885404]},{"file":"\/var\/www\/nextcloud\/apps\/backup\/lib\/Cron\/Backup.php","line":97,"function":"manage","class":"OCA\\Backup\\Cron\\Backup","object":{},"type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/BackgroundJob\/Job.php","line":51,"function":"run","class":"OCA\\Backup\\Cron\\Backup","object":{},"type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/BackgroundJob\/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","object":{},"type":"->","args":[{},{}]},{"file":"\/var\/www\/nextcloud\/cron.php","line":150,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","object":{},"type":"->","args":[{},{}]}]

**Comment by realdarKing** [comment]
There is an OCC command that will reset the config, delete local backup points (= local backup files) _and deactivate_ the App. I hope it is as safe as it feels. :o)

`occ backup:reset --uninstall`

Always do this as the webserver user

for example (this may look different in your case):
`sudo -u www-data php /var/www/nextcloud/occ backup:reset --uninstall`

For me, it does not delete remote files though. You would have to clean that manually.

**Comment by FernandoMarques-Santos** [comment]
Thanks! it worked like a charm. Your solution was handy because I will have a clean config to try the app again in the future since I obviously misconfigured it somehow.
