### ISSUE TITLE
backup is never starting

### ISSUE THREAD

**Issue by gklank** [nextcloud/backup#323]
Hi,

after clicking on "Create full restoring point" the creation is never starting.

Showing a number of hours, but after the time is over = should be the starting point of the creation, nothing happens.
Also I don't find any possibility to stop this request and restart it again.

only showing: The creation of a restoring point as been requested and will be initiated soon.

Any ideas to restart or cancel this task?

Regards

Gerhard

update:
Found error:
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com/

but I have no idea about

**Comment by gklank** [comment]
sorry, did some mistakes, permissions issues as well.

Looks good now.

Thx!

**Comment by AnAnalogGuy** [comment]
If you're problem is solved, you might want to close the ticket?

**Comment by gklank** [comment]
Hi,

I got it fixed, issues are done by my configuration.

Thx and regards,

Gerhard

**Comment by toretino** [comment]
> Hi,
> 
> after clicking on "Create full restoring point" the creation is never starting.
> 
> Showing a number of hours, but after the time is over = should be the starting point of the creation, nothing happens. Also I don't find any possibility to stop this request and restart it again.
> 
> only showing: The creation of a restoring point as been requested and will be initiated soon.
> 
> Any ideas to restart or cancel this task?
> 
> Regards
> 
> Gerhard
> 
> update: Found error: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com/
> 
> but I have no idea about

How do u solved

**Comment by gklank** [comment]
Hi,

sorry, don't remember good enough.

But I was anyway not really happy with this kind of backup.
Therefore I switched to rsyncing of the data- and config-folder.

Regards,

Gerhard
[nextcloudbackup.txt](https://github.com/nextcloud/backup/files/14156935/nextcloudbackup.txt)
