### ISSUE TITLE
after update to nextcloud to 24.0.1 with backup 1.0.6 erros creating files and folders

### ISSUE THREAD

**Issue by nunoleite** [nextcloud/backup#329]
Hi!

I have updated Nextcloud 23.0.4 to 23.0.5 and then to 24.0.1 and everything seemed to be ok.

But then i tried to create a file and see an error "Unable to create file". Then tried to create e folder and the same "Unable to create folder".
After refreshing the page i see the file and folder created.
Then i tried to start disabling some apps and after disabling Backup 1.0.6 the error disappeared and everything seems ok.
I tried to enable Backup again and the error returned.
So, there must be a bug in Backup app or some incompatibility between Nextcloud 24.0.1 and Backup app 1.0.6.

Thanks

**Comment by CedricNanni** [comment]
Hi,

I've got exactly the same issue.

Thanks

**Comment by Tharguard** [comment]
Same here

**Comment by ywattenberg** [comment]
I've been having the same issue. For me it's related to these problems #294 #303 #293 can you confirm if you get the same messages in your logs.
something in the form of this:
```
[no app in context] Error: Exception: OC\DB\QueryBuilder\QueryBuilder::__construct(): Argument #3 ($logger) must be of type Psr\Log\LoggerInterface, OC\Log given, called in /var/www/nextcloud/apps/backup/vendor/artificial-owl/my-small-php-tools/lib/Db/Nextcloud/nc23/NC23ExtendedQueryBuilder.php on line 74 in file '/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php' line 86 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/ocs/v1.php line 62
   OC\Route\Router->match()
3. /var/www/nextcloud/ocs/v2.php line 23
   require_once("/var/www/nextcloud/ocs/v1.php")

GET /ocs/v2.php/apps/backup/r
```

**Comment by nunoleite** [comment]
Confirm.
After installing and activating Backup App, i have the same Errors in the logs:

```
[no app in context] Error: Exception: OC\DB\QueryBuilder\QueryBuilder::__construct(): Argument #3 ($logger) must be of type Psr\Log\LoggerInterface, OC\Log given, called in /home/xxxxx/public_html/apps/fulltextsearch/vendor/artificial-owl/my-small-php-tools/lib/Db/Nextcloud/nc23/NC23ExtendedQueryBuilder.php on line 74 in file '/home/xxxxx/public_html/lib/private/DB/QueryBuilder/QueryBuilder.php' line 86 at <<closure>>

0. /home/xxxxx/public_html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /home/xxxxx/public_html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /home/xxxxx/public_html/ocs/v1.php line 62
   OC\Route\Router->match()
3. /home/xxxxx/public_html/ocs/v2.php line 23
   require_once("/home/xxxxx/public_html/ocs/v1.php")

GET /ocs/v2.php/apps/backup/rp
```

**Comment by Cob0ld** [comment]
same problem, any news on this issue ?

**Comment by ywattenberg** [comment]
Not that I know of apparently as mentioned in #293, the problem seems to be the version of the my-small-php-tools lib that is used is still 23 and 24 is not yet available as far as I know.

**Comment by zwergtimm** [comment]
I have a similar Problem. I cannot acces my external store connected through WebDav and the App than prematurely goes into maintenance mode (before the set time) to try to make a full backup (which it cannot do as there is no storage connected) which causes nextcloud to hardlock in maintenance mode which I then have to manually disable. Is it possible to install the 1.0.5 Version of the app as according to the websit of the app that version is optimized for Nextcloud 24?

**Comment by szaimen** [comment]
I think the app should work with nc24 and 1.1.2 now
