### ISSUE TITLE
Quick compression during 1st pass?

### ISSUE THREAD

**Issue by Alain2019** [nextcloud/backup#340]
Hi

In the documentation there's abullet "Quick compression during 1st pass", but not more info.

Is there a quick compression in the first pass, maybe as an option?  

In the past I've done tests that a bit compression can actually faster than no compression at all.  And it uses less space ;-)

**Comment by ArtificialOwl** [comment]
we got rid of compression on 1st pass. the compression ratio compared to the time spent with the instance in maintenance mode was not interesting at all.
