### ISSUE TITLE
Unable to fetch restoring points | Unable to fetch external locations 

### ISSUE THREAD

**Issue by ISlip3890** [nextcloud/backup#358]
When I go over to the "backup" tab in Administration after installing the app, I am met with "Unable to fetch restoring points & Unable to fetch external locations". This has started ever since I upgraded my installation to Nextcloud: 24.0.2. Any suggestions?

What the error looks like:
![image](https://user-images.githubusercontent.com/74471699/178156749-d156cdf5-0008-4683-a291-3e75528d4aac.png)

**Comment by deetuned** [comment]
I'm experiencing the exact same issue. Backup app is 1.1.2 and Nextcloud is 24.0.4.

**Comment by lroyb** [comment]
I had the same problem... I fixed it by changing the file permissions on the share

**Comment by ISlip3890** [comment]
> I had the same problem... I fixed it by changing the file permissions on the share


What did you change the directory permissions to?

**Comment by lroyb** [comment]
I allowed the smb username, full file ownership, while keeping the group as the wheel group. I chmodded the folder to 660.

i'm running 24.0.4
