### ISSUE TITLE
Support Nextcloud 24

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/backup#363]
Please see title

**Comment by AnAnalogGuy** [comment]
https://github.com/nextcloud/backup/issues/342

**Comment by Alain2019** [comment]
any news, this is blocking upgrading.

Or I have to find another solution

**Comment by szaimen** [comment]
I think nc24 should work with 1.1.2 https://github.com/nextcloud-releases/backup/releases/tag/v1.1.2

**Comment by AnAnalogGuy** [comment]
Good to see somone from NC react but to be honest "I think it should" is not good enough.
Don't you guys have testing in place?
For me, it looks like this piece of software at its state should be alpha or beta but not production ready. We are mainly missing professional software management, such as release planing, release documentation, testing, communication/support. 
If you need help to establish these compentences, please ping me.

**Comment by szaimen** [comment]
> Good to see somone from NC react but to be honest "I think it should" is not good enough.

I am not the maintainer. I simply asked the person in question and he said it works with the latest release.

**Comment by AnAnalogGuy** [comment]
Who is the maintainer?

**Comment by szaimen** [comment]
https://github.com/nextcloud/backup/graphs/contributors
