### ISSUE TITLE
Where can the recent changelogs and release downloads be found?

### ISSUE THREAD

**Issue by deetuned** [nextcloud/backup#410]
I cannot find anything past v1.0.6 which is a major problem since backups are still broken in Nextcloud v24 and I cannot seem to find a way to download Backup v1.1.3 manually.

**Comment by nssatlantis** [comment]
Same deal, seeing what's been changed would be a nice standard to uphold

**Comment by solracsf** [comment]
See here for releases and changelogs: https://github.com/nextcloud-releases/backup/releases/

**Comment by danepowell** [comment]
If https://github.com/nextcloud-releases/backup/releases/ is the canonical list of changes, can you please link to that from the Changelog and/or readme? I had no idea that page existed. Since there's no releases page on this project, I assumed the Changelog was canonical.
