### ISSUE TITLE
Backup app kills the config.php file

### ISSUE THREAD

**Issue by juliensl** [nextcloud/backup#421]
Hi everybody, 

I am reporting an issue that can happen when backup app is uncorrectly used.

My problem appeared in 2022 April, but some people have it just few days ago, step to reproduce : 

- Begin the backup
- Your disk become full because you do not have enough space
- The backup and server crash
- You delete the backup folder
- You cannot connect yourself again to your server because the config.php file has been cleaned

Exemple of a config.php file after : 
```
$CONFIG = array (
  'instanceid' => 'oc8ig6j7n1sq',
);
```

Actually, thanks to @kyrofa, we succeed to re-create a new config.php file, so I do not need help anymore.
But the problem could happen for other people.

Maybe you should add a "space verificator" before to begin the backup, to not fullfill the disk.

To see all the sources, you can find my first post here : 
https://help.nextcloud.com/t/disk-full-after-trying-to-backup/144556 
And my comments here : https://github.com/nextcloud-snap/nextcloud-snap/issues/2162

Just to know, I am using Nextcloud with snap on an Ubuntu server.

Thank you for your work !

**Comment by ArtificialOwl** [comment]
this might be fixed by https://github.com/nextcloud/server/pull/34009

**Comment by ArtificialOwl** [comment]
tested and can confirm it will be fixed in next release of NC
