### ISSUE TITLE
NC 25: Can't see the numbers in settings

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/backup#424]
![grafik](https://user-images.githubusercontent.com/24530680/190328096-fc18431b-6350-49b6-81fe-0f5e1f6710aa.png)

With NC24 (same browser it's working)
![grafik](https://user-images.githubusercontent.com/24530680/190328175-8e546e41-4ba3-4bf5-9087-5e25d007ce0e.png)

**Comment by sibiantony** [comment]
PR submitted #445
