### ISSUE TITLE
Add support for NC 25

### ISSUE THREAD

**Issue by kboss** [nextcloud/backup#454]
As Nextcloud 25 is now distributed on stable it would be nice to have backup supporting it.

**Comment by CryPt00n** [comment]
Even if currently not supported, did someone tested it with nextcloud running in docker and postgresql as database?

**Comment by schwerg** [comment]
Any update on this?

**Comment by Dieter-W** [comment]
Any update on this?

**Comment by Aquariu** [comment]
A duplicate issue has been created recently that bring screenshots of the backup app having issues connecting with the database with special characters in the password.

**Comment by PVince81** [comment]
@ArtificialOwl please update the backup app to make it ready for 25 and upcoming 26. thanks

**Comment by kboss** [comment]
Release of version 1.2.0 solved the issue. Thx
