### ISSUE TITLE
Special character handling in PostgreSQL credentials

### ISSUE THREAD

**Issue by cgallay** [nextcloud/backup#469]
Hi,

I am having difficulties performing backups on the new version of nextcloud.
![image](https://user-images.githubusercontent.com/3649143/211269298-f41014e9-5de3-4148-9737-db86bf3ffa7d.png)

I am not able to make the application work on the UI side. Therefore I have tried to make it work using the cli but got that issue.
![photo_2023-01-09 09 47 10](https://user-images.githubusercontent.com/3649143/211269582-6a34c1b0-1ac8-4c3c-987a-a1dafbbf2546.jpeg)

I was able to fix it by removing special characters from my DB password but I don't think this should be a vaiable solution.

Any plan on when the application will be fully compatible with nextcloud 25?

If there is anything I can do to help please let me know.

Charles

**Comment by cgallay** [comment]
Thanks for your response @LeLuc4 which exact version of nextcloud and which version of backup app are you using?

**Comment by LeLuc4** [comment]
Nextcloud: 25.0.2 (via AIO)
Backup: 1.2.0

**Comment by joshtrichards** [comment]
Fixed in #585
