### ISSUE TITLE
I get an error when activating the plugin in apps, it says "Could not download app backup". Is this plugin for the paid version?

### ISSUE THREAD

**Issue by Spideloy** [nextcloud/backup#508]

**Comment by Kisaragi-ng** [comment]
afaik This plugin has no "paid version". If it says 'could not download app backup," you have to check the log to see whether it's a name resolution failure or folder permission issue.

**Comment by joshtrichards** [comment]
Indeed. What @Kisaragi-ng said. This seems to be a config/troubleshooting matter rather than a bug in this app. For further help, use the help forum: https://help.nextcloud.com
