### ISSUE TITLE
Optimization for nextcloud 26.0.0

### ISSUE THREAD

**Issue by H3nSte1n** [nextcloud/backup#512]
Nextcloud displays a message that the compatible version is missing for nextcloud 26.

<img width="498" alt="grafik" src="https://user-images.githubusercontent.com/23628956/228880046-3c939b5d-746a-4254-a629-fa09fe2c45c9.png">

**Comment by ojsef39** [comment]
Did you update nonetheless? I need some feedback if the app works properly, even though it hasn't got an update for NC 25 and 26.
Thanks in advance! :)

**Comment by ojsef39** [comment]
> It does not work. I just get a blank screen.

Thanks for your feedback. I'm going now another route anyway. I will back up the VM in Proxmox to an external Storage directly instead of only the Nextcloud data via the app.

**Comment by flyize** [comment]
While I totally understand this is what can happen with FOSS, it's still crazy to me that backup seem to be a low priority.

**Comment by handkerchief333** [comment]
Same here for  Backup 1.2.0:
`Server version 25 or lower is required. `

I use nextcloud version 26.0.1

this is by far the most important app, would be great if this app was actively developed and available for the latest nextcloud versions :slightly_smiling_face:

**Comment by WeAppU** [comment]
Same Problem here with 26.0.2.1 :-(

**Comment by nathan-gilbert** [comment]
Same boat here -- really need this app for v26

**Comment by joshtrichards** [comment]
Fixed in #598
