### ISSUE TITLE
support for Nextcloud v26

### ISSUE THREAD

**Issue by jmcisvt** [nextcloud/backup#553]
Will the Backup app work with v26 at some point?

**Comment by nathan-gilbert** [comment]
Same question here -- looking to try this out but am on v26

**Comment by ani-tvm** [comment]
thanks in advance. it is possible to restore a single file by  sudo -u apache php occ  backup:point:restore --file ......

**Comment by ShadabFaiz** [comment]
seems like this is dead

**Comment by benzkji** [comment]
hm. this is an official app, developed be nextcloud itself, isn't it? strange...

**Comment by Dieter-W** [comment]
I would also like to know what's the status of this app.

**Comment by karlemilnikka** [comment]
> I would also like to know what's the status of this app.

I’m in no way representing the developer, but I think the developer has sent a clear signal. I wouldn’t use the app even if they released an update now. By not keeping the app up-to-date with the rest of the Nextcloud project, it isn’t an app to rely upon for something as critical as backups. 

Nextcloud 28 is planned for release next week. The latest supported version of the backup app is Nextcloud 25, which [went out of security maintenance two months ago](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule). I’d recommend the Nextcloud team to delist the app.

**Comment by Dieter-W** [comment]
Thanks for the answer.  It's what I like to hear, but better to remove the app, rather to get security problems.

**Comment by karlemilnikka** [comment]
> Well, anyone have good alternatives for backing up Nextcloud?

BorgBackup is built-in into Nextcloud AIO (if you’re using AIO).

**Comment by Krautmaster** [comment]
want to migrate from Nextcloud 27 on a jail to nextcloud 27 in a truecharts truenas scale app and thought a real backup app could do that job. But this one sucks, lists no backup points. Any idea how to do so in NC27?

**Comment by joshtrichards** [comment]
Fixed in #598
