### ISSUE TITLE
unlink No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Helper.php

### ISSUE THREAD

**Issue by Felzomah** [nextcloud/backup#676]
Since a week I get thousands of error messages about unlink no such file or directory always from OC_Helper.php, for example:

unlink(/tmp/oc_tmp_SiLd7w): No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Helper.php

{"reqId":"NLyfUvxfTXNxAKm98CTp","level":3,"time":"2024-05-21T10:15:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"unlink(/tmp/oc_tmp_SiLd7w): No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#200","userAgent":"--","version":"29.0.0.19","data":{"app":"PHP"},"id":"664c742c5c867"}

The error has no further calltrace.

Nextcloud version: 29.0.1.1
Operating system and version: Ubuntu 22.04 LTS
Apache or nginx version: Apache 2.4.52
PHP version: 8.2

Server uses external SMB/CIFS folders.
Maybe it started since updating to the new php 8.2.19.

```
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'next.xyz.de',
    1 => '192.168.115.7',
    2 => 'localhost',
  ),
  'datadirectory' => '/var/nextcloud_data',
  'dbtype' => 'mysql',
  'version' => '29.0.1.1',
  'overwrite.cli.url' => 'http://192.168.115.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud_db_user',
  'dbpassword' => '***',
  'updater.release.channel' => 'stable',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'xyz.de',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.xyz.de',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'info@xyz.de',
  'mail_smtppassword' => '321',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'maintenance_window_start' => 1,
  'theme' => '',
  'loglevel' => 2,
  'app_install_overwrite' => 
  array (
    0 => 'keeporsweep',
    1 => 'user_saml',
    2 => 'htmlwidget',
    3 => 'unsplash',
    4 => 'apporder',
    5 => 'breezedark',
    6 => 'files_mindmap',
    7 => 'shifts',
    8 => 'carnet',
    9 => 'quicknotes',
    10 => 'occweb',
  ),
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'installed' => true,
  'default_phone_region' => 'ISO 3166-2:DE',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 1.5,
    'read-timeout' => 1.5,
  ),
  'defaultapp' => '',
  'enforce_theme' => '',
);
```

How to proceed and to find more information to debug this error?

**Comment by smolinde** [comment]
I have the exact same problem and was forced to disable Backup. It is probably not a PHP error since I use version 8.3 and also run into this issue. The problem behind this is the simple fact that Backup is not compatible with NC 29.x yet, which, I hope, will  be fixed soon.

**Comment by Felzomah** [comment]
It turned out, that cron was running cron.php twice.
