### ISSUE TITLE
NC 23 RC2 + backup 1.0.0-beta3: activitiy not loading with backup app enabled

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/backup#69]
I installed the backup app, played around with it, did some backups and now the activity is not loading for my root user:
![image](https://user-images.githubusercontent.com/24530680/141740897-0ff8b249-feac-4036-b220-4dc865b29e4f.png)
If I disable the backup app, activty is loading

**Comment by ArtificialOwl** [comment]
do you have anything in the logs ?

**Comment by jakobroehrl** [comment]
> do you have anything in the logs ?

This comes up every time I reload the activity: 
https://github.com/nextcloud/circles/issues/844

I get a 500 on the request:

![image](https://user-images.githubusercontent.com/24530680/141836874-28f097d1-af65-4f50-8ffb-22c16fb942fa.png)
Response: {"ocs":{"meta":{"status":"failure","statuscode":500,"message":"Internal Server Error\n"},"data":[]}}

**Comment by jakobroehrl** [comment]
solved with RC3
