### ISSUE TITLE
How to install backup on NC 21?

### ISSUE THREAD

**Issue by xpom43** [nextcloud/backup#77]
Hello, how do I install a backup on the NC 21?

**Comment by ggeorgg** [comment]
Minimum version for this app is nextcloud 23 as you can see for example directly in the code here https://github.com/nextcloud/backup/blob/d843dd4319734ba4e8f11e6e5d5d4113d9c6a45f/appinfo/info.xml#L31
or here https://apps.nextcloud.com/apps/backup if you scroll down.
I guess this app uses features which are not yet present in the code of nextcloud 21 or 22.

**Comment by ArtificialOwl** [comment]
if you edit the min-version to 21, you might be able to run the app on your instance of Nextcloud. 
However, the app is made for NC23, so you might encounter some issues that won't be supported.
