### ISSUE TITLE
Need context for translation

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/backup#78]
https://github.com/nextcloud/backup/blob/7cf5dda097987ea44e72a7889c4f8e1fb368946b/src/components/GeneralSettingsSection.vue#L82

What does packing a restore point mean?

Question has been placed as an issue at Transifex.

**Comment by ArtificialOwl** [comment]
Packing is the process to compress and/or encrypt your restoring point. The definition can be find in [README](https://github.com/nextcloud/backup#the-second-pass-the-packing-process)

**Comment by rakekniven** [comment]
Thanks.
