### ISSUE TITLE
rsync hard links

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/backup#8]
rsync should automatically use hard links to save storage

**Comment by karlitschek** [comment]
The rsync option is 'link-dest' More information is here: http://earlruby.org/2013/05/creating-differential-backups-with-hard-links-and-rsync/#comment-1835

**Comment by IzumiSena** [comment]
Frank bro why this app development stop?

**Comment by ArtificialOwl** [comment]
we don't use rsync anymore
