### ISSUE TITLE
Unable to fetch app data

### ISSUE THREAD

**Issue by zarevskaya** [nextcloud/backup#92]
Hello, 

I have a message when i load the Backup page: Unable to fetch app data.

Impossible to clic on the botton "Set as App Data"

I don't know if this log can help.

```
[PHP] Error: include(/config/www/nextcloud/apps/backup/vendor/composer/../symfony/polyfill-php80/Php80.php): failed to open stream: No such file or directory at /config/www/nextcloud/lib/composer/composer/ClassLoader.php#571

GET /ocs/v2.php/cloud/groups?offset=0&search=&limit=5
from 192.168.1.25 by zarev at 2021-11-30T19:20:32+00:00
```

or

```
[PHP] Error: include(): Failed opening '/config/www/nextcloud/apps/backup/vendor/composer/../symfony/polyfill-php80/Php80.php' for inclusion (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') at /config/www/nextcloud/lib/composer/composer/ClassLoader.php#571

GET /ocs/v2.php/cloud/groups?offset=0&search=&limit=5
from 192.168.1.25 by zarev at 2021-11-30T19:20:32+00:00
```

or

```
2021/12/01 07:41:36 [error] 407#407: *320 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused in /config/www/nextcloud/lib/private/DB/Connection.php:87
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /config/www/nextcloud/lib/private/DB/Connection.php(236): Doctrine\DBAL\Connection->executeQuery()
#3 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /config/www/nextcloud/lib/private/AppConfig.php(344): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /config/www/nextcloud/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
```

After delete & reinstall the App, same error.

**Comment by ArtificialOwl** [comment]
I will try to replicate your issue, which database are you using ?

**Comment by zarevskaya** [comment]
Hello,

Mariadb under Docker.
Nextcloud under Docker too.

**Comment by ArtificialOwl** [comment]
strange, tested under same config, no issue on my side. Did you install the app from the appstore or the repository ?

**Comment by zarevskaya** [comment]
From the appstore.

Do you want to do a Anydesk to see that?

**Comment by ArtificialOwl** [comment]
I am really dubious on the fact that the issue comes from the backup app. 
Can you confirm that you have no error in the logs when the app is disabled ?

**Comment by zarevskaya** [comment]
![fletch](https://user-images.githubusercontent.com/60230221/144460011-a8714786-48ab-436b-aac2-5f5ec30d850c.png)

I have disabled now. 

But this log is from backup:

![Capture d’écran 2021-12-02 171521](https://user-images.githubusercontent.com/60230221/144460259-6b1462d0-c9bf-4551-8a71-e998295ea926.jpg)

**Comment by ArtificialOwl** [comment]
It seems it is missing a table ?

try:

`./occ backup:reset --uninstall`
`./occ app:enable backup`

This will fully uninstall the app and remove your backups if you have any.

**Comment by zarevskaya** [comment]
I had try and voilà:

![Capture d’écran 2021-12-03 155902](https://user-images.githubusercontent.com/60230221/144623870-678aab98-1462-488a-a3a2-d3d0f66494b3.jpg)

**Comment by ArtificialOwl** [comment]
please run `./occ backup:reset --uninstall -v`

**Comment by zarevskaya** [comment]
I have the same problem again 
He keeps bad information in his memory

![Capture d’écran 2021-12-03 180607](https://user-images.githubusercontent.com/60230221/144643613-31f9579f-d3dd-4e43-a5df-44dcdf5ac1d1.jpg)

![Capture d’écran 2021-12-03 180713](https://user-images.githubusercontent.com/60230221/144643628-8ea67965-7740-4d95-855d-ebc2455eea09.jpg)

**Comment by morskipas** [comment]
I have exactly the same problem. My environment Nextcloud with Maria DB all based on Docker.

**Comment by zarevskaya** [comment]
@morskipas 
Do you have the same logs as me?

**Comment by morskipas** [comment]
> @morskipas Do you have the same logs as me?
That's really weird, I just checked the logs and found that no entry was created in the logfile since the update to version 23. As no more entries the last 3 days.

**Comment by zarevskaya** [comment]
It's bad luck 🤷🏻‍♂️

Let's wait to see...

**Comment by morskipas** [comment]
Now the error message is gone, my problem was that I forgot to add /home/ at the beginning

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/6042276/144756727-4052af5e-6824-4c53-b92e-3b9223432a0c.png">

**Comment by morskipas** [comment]
> It's bad luck 🤷🏻‍♂️
> 
> Let's wait to see...

So ... this hint in the documentation was the solution for me


Known issues:
When adding a new external storage from the files_external, the folder needs to be mounted using the Files App. Browsing the root folder should be enough.

**Comment by zarevskaya** [comment]
Happy to you :)

Me, it's a little bit different:
![problem](https://user-images.githubusercontent.com/60230221/144758401-89cb3ed8-8591-4105-a82a-3e63b8ffcc20.jpg)

**Comment by morskipas** [comment]
> Happy to you :)
> 
> Me, it's a little bit different: ![problem](https://user-images.githubusercontent.com/60230221/144758401-89cb3ed8-8591-4105-a82a-3e63b8ffcc20.jpg)

And you created an external storage and after the creation you can access this storage in "file browser"?

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/6042276/144759116-4d562659-7c71-402d-abee-326a1ecba52f.png">

**Comment by zarevskaya** [comment]
yes it worked for a while, but it can't reach the application data. or something like that

**Comment by morskipas** [comment]
> yes it worked for a while, but it can't reach the application data. or something like that

I also had the same error when I didn't have permissions to read the directory (in my case /app-backup). Can you access the specified directory in the file browser?

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6042276/144759831-5e7035d1-b462-45bc-9c1a-1e3b056c0481.png">

**Comment by zarevskaya** [comment]
Yes, i can:
![access](https://user-images.githubusercontent.com/60230221/144759992-e9ce0cee-7c5b-4831-bc67-401d173997d8.jpg)

**Comment by morskipas** [comment]
> Yes, i can: ![access](https://user-images.githubusercontent.com/60230221/144759992-e9ce0cee-7c5b-4831-bc67-401d173997d8.jpg)
> 
> But: ![Capture d’écran 2021-12-05 200707](https://user-images.githubusercontent.com/60230221/144760065-1a03a6bb-d6e9-4354-a40c-44efb1c0434e.jpg)

Then I'm really sorry and I can not help either :-(

**Comment by zarevskaya** [comment]
No problem, thank you very much to had try ;)

Have a nice day!

**Comment by ArtificialOwl** [comment]
Could it be that your HTTPD's userid have no right to create the /home/app_data/ ? 

You should create a folder named `backups` and give `www-data` permissions

**Comment by ArtificialOwl** [comment]
@zarevskaya 

> I have the same problem again He keeps bad information in his memory
> 
> ![Capture d’écran 2021-12-03 180607](https://user-images.githubusercontent.com/60230221/144643613-31f9579f-d3dd-4e43-a5df-44dcdf5ac1d1.jpg)
> 
> ![Capture d’écran 2021-12-03 180713](https://user-images.githubusercontent.com/60230221/144643628-8ea67965-7740-4d95-855d-ebc2455eea09.jpg)

About this, I made a [small patch](https://github.com/nextcloud/backup/pull/98.diff) if you want to try a full uninstall of the app. If you don't want to apply the patch, you can at least try to disable the app files_external before:

- `./occ app:disable files_external`
- `./occ backup:reset --uninstall`
- `./occ app:enable files_external`

**Comment by zarevskaya** [comment]
> Could it be that your HTTPD's userid have no right to create the /home/app_data/ ?
> 

![Capture d’écran 2021-12-06 140913](https://user-images.githubusercontent.com/60230221/144851667-0a7e3279-6d3b-41ca-8a8b-1303469e01ed.jpg)
> You should create a folder named `backups` and give `www-data` permissions
![Capture d’écran 2021-12-06 141055](https://user-images.githubusercontent.com/60230221/144851913-7d3b98d3-f73b-4ff5-9e3b-5af9418bbd88.jpg)

I try the rest 👍

**Comment by ArtificialOwl** [comment]
I will release 1.0.1 later, in the meanwhile, you might want to have a look to https://github.com/nextcloud/backup/issues/102#issuecomment-987959633

**Comment by zarevskaya** [comment]
I saw but that's not the problem because at the beginning everything worked. If the external backup does not work with privatekey, okay,but it should work locally.
