### ISSUE TITLE
Unable to complete a full backup

### ISSUE THREAD

**Issue by Dartoxian** [nextcloud/backup#97]
Hi, I've just upgraded to Nextcloud 23 and was excited to test out this new Backup app. 

I've configured it to write to an S3 compatible external storage (Digital Ocean space) for both `app_data` and the `backup` directory. I can see that files are being written to my external storage, however the full backup job keeps failing - then restarting and writing a fresh full backup to my external storage. It seems that it must be getting quite far through the backup process as my external storage is filling up quite quickly (after letting the backup job run overnight it had used over 300GB of storage!).

I'm using version `1.0.0` of the app. My `data` directory is around 23GB.

I notice in my external storage that the `app_data` directory is being populated, but the `backups` directory is not.

I've copied the stack trace below that I've found repeatedly in my logs.

```
{
  "reqId": "zL8ilThAAVvq2vETkEAB",
  "level": 0,
  "time": "2021-12-04T12:27:59+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "backup",
  "method": "",
  "url": "--",
  "message": "error while running full backup - [{\"file\":\"\\/var\\/www\\/html\\/custom_apps\\/backup\\/lib\\/Cron\\/Backup.php\",\"line\":113,\"function\":\"runFullBackup\",\"class\":\"OCA\\\\Backup\\\\Cron\\\\Backup\",\"object\":{},\"type\":\"->\",\"args\":[]},{\"file\":\"\\/var\\/www\\/html\\/custom_apps\\/backup\\/lib\\/Cron\\/Backup.php\",\"line\":104,\"function\":\"runBackup\",\"class\":\"OCA\\\\Backup\\\\Cron\\\\Backup\",\"object\":{},\"type\":\"->\",\"args\":[1638619825]},{\"file\":\"\\/var\\/www\\/html\\/lib\\/private\\/BackgroundJob\\/Job.php\",\"line\":51,\"function\":\"run\",\"class\":\"OCA\\\\Backup\\\\Cron\\\\Backup\",\"object\":{},\"type\":\"->\",\"args\":[null]},{\"file\":\"\\/var\\/www\\/html\\/lib\\/private\\/BackgroundJob\\/TimedJob.php\",\"line\":58,\"function\":\"execute\",\"class\":\"OC\\\\BackgroundJob\\\\Job\",\"object\":{},\"type\":\"->\",\"args\":[{},{}]},{\"file\":\"\\/var\\/www\\/html\\/cron.php\",\"line\":128,\"function\":\"execute\",\"class\":\"OC\\\\BackgroundJob\\\\TimedJob\",\"object\":{},\"type\":\"->\",\"args\":[{},{}]}]",
  "userAgent": "--",
  "version": "23.0.0.10"
}
```

Since the app is consuming so much storage I've disabled it for now, but if there are any additional debugging steps you'd like me to take, please let me know and I'll enable it again.

**Comment by ArtificialOwl** [comment]
Hello,

Thanks for your report, 

Until #94 is merged, the only way to know better about this issue is to run the backup manually:

`./occ backup:point:create`

Enable the app, run this command and check the terminal for details about the issue.
Disable the app afterward to not run faulty background backups :)

**Comment by ArtificialOwl** [comment]
Also, it is normal that `app_data` is filled but not `backups`. `backups` will only contains packed backup (2nd pass), while `app_data` contains local/current backup

You can find more detailed explanation [here](https://github.com/nextcloud/backup/blob/master/README.md#the-first-pass-the-backup-process)

**Comment by Dartoxian** [comment]
Thanks for getting back to me @ArtificialOwl.

Running `./occ backup:point:create` has revealed the problem:

```
PHP_MEMORY_LIMIT=1g ./occ backup:point:create
> maintenance mode: on
> initialization of the AppData
> initialization of the RestoringPoint: 20211207165819-full-qptHDRiVhsm63XU based on NC23.0.0.10
> initialization of the storage
> preparation of the data to be stored in the restoring point
> preparation of internal data
> creating chunks
  * data: /var/www/html/data/, 30406 files
    - data-b0978c55-7d0d-49f2-b9c8-abdac15e209b
    - data-646f85e1-d67b-4eda-81f1-93d5ad8ad524
    - data-93fc7eb6-469b-4db5-9c4a-dc6494d179f5
    - data-e440c650-a27d-4c92-b02c-25e6241638c2
    - data-ade22066-0f62-4137-b2a7-a97c30ae7623
    - data-37c76d3d-1163-40fb-a1a9-8371a79f8567
  * nextcloud: /var/www/html/, 11176 files
    - nextcloud-40907552-96e4-4e25-b834-dc2f0e9dbfca
  * apps: /var/www/html/apps/, 10237 files
    - apps-05f24673-fe28-4150-a9d3-ab595ba919db
  * config: /var/www/html/config/, 1 files
    - config-5e66e43c-ed7c-4532-a89d-e0288c19b19c
  * apps-apps-9e970929: /var/www/html/apps, 10237 files
    - apps-apps-9e970929-e194117a-6813-4847-93f3-3e3715ec6ee0
  * apps-custom_apps-78c2fad5: /var/www/html/custom_apps, 1737 files
    - apps-custom_apps-78c2fad5-40881f22-c808-447c-b3d9-87b4865fceab
  * SqlDump: OCA\Backup\SqlDump\SqlDumpPgSQL
    - exporting sql to /tmp/phpX6WLAV
> maintenance mode: off

In SqlDumpPgSQL.php line 80:
                                                                                             
  The dump process failed with exitcode 127 : Command not found : sh: 1: pg_dump: not found  
                                                                                             

backup:point:create [--output [OUTPUT]] [--differential] [--] [<comment>]
```

I run Nextcloud as a container in a nomad cluster. My nextcloud dockerfile is in this repo https://github.com/sageroom/nextcloud. The image is based on the official `23.0.0-apache` image.

I've updated my image to include `postgresql-client` and now the first stage of the backup completes successfully - it's not started packing yet.

**Comment by thomasesr** [comment]
I'm also having this issue on official nextcloud:latest docker image. 
`
The dump process failed with exitcode 127 : Command not found : sh: 1: pg_dump: not found`

**Comment by ywattenberg** [comment]
I'm also running the official docker image (`nextcloud:apache`) with postgresql through docker-compose and have the same problem  as @thomasesr.
My the backup fails with
`The dump process failed with exitcode 127 : Command not found : sh: 1: pg_dump: not found`

**Comment by Saxfusion** [comment]
Similar error (only full - pass 1 backup trial, no 2nd pass / external dump), but native with Apache2.4/PHP7.4/MariaDB 10

`  * SqlDump: OCA\Backup\SqlDump\SqlDumpMySQL
    - exporting sql to /tmp/phpsLzY39
> maintenance mode: off

In SqlDumpMySQL.php line 91:
                                                                                      
  Connection to mysql failed with message: SQLSTATE[HY000] [2002] Connection refused `

Any ideas on how to single out the reason since the NC instance itself has no trouble reading/writing to the DB?
